pipeline {
    agent any
    stages {
        stage('Data Preprocessing') {
            steps {
                script {
                    sh 'python src/preprocess_data.py'
                }
            }
        }
        stage('Model Training') {
            steps {
                script {
                    sh 'python src/train_model.py'
                }
            }
        }
        stage('Testing') {
            steps {
                script {
                    sh 'python src/test_model.py'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t anomaly-detection:latest src/.'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 5000:5000 anomaly-detection:latest'
                }
            }
        }
    }
}
